Layout/AlignArguments:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/SendWithMixinArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Next:
  Enabled: false
